CupCarbon v. Twin IoT 6.52
----------------
name:mvp Smartlab
zoom:0
centerposition_la:4.602907023330615
centerposition_lo:-74.06466364860535
map:0
display_details:false
draw_radio_links:true
draw_sensor_arrows:false
radio_links_color:2
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
display_all_routes:true
